mono/libgdiplus

- src/gifcodec.c
Based on https://github.com/pld-linux/libgdiplus/blob/master/libgdiplus-giflib.patch
> Fixed compilation with giflib version 5

- src/pngcodec.c
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=27616.
> Fix libgdiplus to handle 2bpp color PNG files

- src/region.c
- src/region.h
> Fix missing symbols in region on Windows

- src/adjustablearrowcap.c
- src/adjustablearrowcap.h
And fix IDE warnings for float used instead of REAL
> Fix adjustable arrow cap symbols with Win32

- tests/testgraphics.c
About half of these fail with libgdiplus - I'll submit a PR fixing them after this
> Add more graphics tests

- src/graphics.c
- src/graphics.h
- src/win32structs.h
- tests/testgraphics.c
For compat with Windows. And add some tests
> Add stub implementations of missing HWND/HDC APIs

- README
The old instructions were incorrect
I also expanded on the dependencies on OSX
> Update docs for building on OSX/Linux

- tests/.gitignore
- tests/Makefile.am
- tests/testpen.c
Spotted these in https://github.com/dotnet/corefx/commit/fc68efe69fe86793956debbaf2c04ec971cfa9f3#diff-27fd4c118b54b06e4c8b864275a3c06aR644
> Add Pen tests

- .gitignore
Based off https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore
> Add vs code gitignore

- src/bitmap.c
- src/bmpcodec.c
- src/emfcodec.c
- src/emfplus.c
- src/graphics-metafile.c
- src/graphics-path.c
- src/graphics.c
- src/image.c
- src/imageattributes.c
- src/lineargradientbrush.c
- src/metafile.c
- src/pathgradientbrush.c
- src/region-bitmap.c
- src/region.c
- src/text-cairo.c
- src/wmfcodec.c
Unused variables and functions
> Fix some Clang warnings and static analyzer warnings

- src/pathgradientbrush-private.h
- src/pathgradientbrush.c
- src/pathgradientbrush.h
- tests/.gitignore
- tests/Makefile.am
- tests/testpathgradientbrush.c
Add tests, fix libgdiplus, expose missing APIs
> Add PathGradientBrush tests, fix combat bugs, expose new APIs

- src/metafile.c
Extracted from https://github.com/mono/libgdiplus/pull/28
> Fix invalid check in gdip_metafile_Arc

- tests/.gitignore
- tests/Makefile.am
- tests/testbrush.c
> Add brush negative tests

- src/carbon-private.c
- src/font.c
- src/graphics.c
- src/metafile.c
- src/pngcodec.c
With these changes the build is now warning clean on OSX/clang for me.
> Cleanup warnings

- .jenkins-linux.sh
- .travis.yml
- Makefile.am
- configure.ac
- src/gifcodec.c
- src/jpegcodec.c
- tests/testfont.c
- tests/testgraphics.c
- tests/testhelpers.h
- tests/testlineargradientbrush.c
- tests/testpathgradientbrush.c
Ensures we build without warnings.
> Add --enable-warnaserror flag to configure and enable in CI

- src/matrix.c
- tests/.gitignore
- tests/Makefile.am
- tests/testhelpers.h
- tests/testmatrix.c
- tests/testpathgradientbrush.c
Related: https://github.com/dotnet/corefx/pull/24238
> Add Matrix tests and fix compat bugs

- src/imageattributes.c
- src/imageattributes.h
- tests/.gitignore
- tests/Makefile.am
- tests/testimageattributes.c
> Add ImageAttribute tests and fix compat bugs

- src/lineargradientbrush.c
- tests/testlineargradientbrush.c
Requires https://github.com/mono/mono/pull/5672
(Will fail until then)
> Fix LinearGradientBrush validation

- tests/testadjustablearrowcap.c
- tests/testgpimage.c
- tests/testgraphics.c
- tests/testhelpers.h
- tests/testmatrix.c
- tests/testpathgradientbrush.c
- tests/testpen.c
- tests/testpng.c
- tests/teststringformat.c
- tests/testtexturebrush.c
No longer appear in stack traces etc
> Make assertion helpers easier to debug

- src/region-bitmap.c
- src/region-path-tree.c
- src/region-path-tree.h
- src/region-private.h
- src/region.c
I’ve separated this from the other PR as the changes here are more wide ranging
Probably best reviewed with ?w=1
> Handle failures allocating memory in region.c

- README.md
> Add pkg-config to brew dependencies

- .gitignore
Taken from https://github.com/github/gitignore/blob/master/Global/Windows.gitignore
> Update gitignore for Windows

- tests/teststringformat.c
Found with asan
Also clean up some ifdefs
> Fix stack buffer overflow in teststringformat.c

- src/bitmap.c
- src/bmpcodec.c
- src/brush.c
- src/font.c
- src/general.c
- src/gifcodec.c
- src/graphics-cairo.c
- src/graphics-metafile.c
- src/graphics-path.c
- src/graphics.c
- src/hatchbrush.c
- src/image.c
- src/imageattributes.c
- src/jpegcodec.c
- src/matrix.c
- src/pathgradientbrush.c
- src/pen.c
- src/pngcodec.c
- src/region-bitmap.c
- src/region-path-tree.c
- src/region.c
- src/solidbrush.c
- src/text-cairo.c
- src/text-metafile.c
- src/texturebrush.c
- src/tiffcodec.c
- tests/testbits.c
- tests/testgdi.c
- tests/testpathgradientbrush.c
This makes the code a lot more readable and consistent - not sure if we want this in the git history but putting it out here anyway
> Fixup whitespace in source code

- src/bmpcodec.c
- tests/testbmpcodec.c
- tests/testgpimage.c
- tests/testhelpers.h
- tests/testpngcodec.c
> Fix BMP image flags with DPI

- tests/testadjustablearrowcap.c
- tests/testbrush.c
- tests/testcustomlinecap.c
- tests/testfont.c
- tests/testgpimage.c
- tests/testgraphics.c
- tests/testhatchbrush.c
- tests/testhelpers.h
- tests/testimageattributes.c
- tests/testlineargradientbrush.c
- tests/testmatrix.c
- tests/testpathgradientbrush.c
- tests/testpen.c
- tests/testpng.c
- tests/testreversepath.c
- tests/testsolidbrush.c
- tests/teststringformat.c
- tests/testtexturebrush.c
> Get tests building on Windows libgdiplus/gdi+

- src/codecs-private.h
- src/gdipenums.h
- src/gifcodec.c
- src/gifcodec.h
- src/image.c
- src/jpegcodec.c
- src/jpegcodec.h
- src/pngcodec.c
- src/pngcodec.h
- src/tiffcodec.c
- src/tiffcodec.h
- tests/testgpimage.c
> Add encoder parameters for gif, tiff and png. Fix jpeg

- src/libgdiplus.vcxproj
> Copy missing dlls on Windows

- .travis.yml
> Run System.Drawing corefx tests in CI

- src/bmpcodec.c
- tests/testbmpcodec.c
> Don't allow decoding bmp files with missing final line

- src/metafile.c
- src/win32structs.h
> Restore EMF pen behaviour and increase compatability with WMF pen behaviour

- src/gifcodec.c
Rules out our code harming things in https://github.com/mono/libgdiplus/pull/196
This also gives us some additional checks for invalid data!
> Update DGifSlurpMono to match upstream giflib

- tests/.gitignore
- tests/testtext.c
> Add testtext to the gitignore

- src/bitmap.c
- tests/testbitmap.c
And simplify it at the same time to use GdipCreateBitmapFromScan0
> Fix GdipCreateBitmapFromGraphics to actually use the graphics

- src/bitmap.c
- src/image.c
- tests/testbitmap.c
- tests/testgpimage.c
Fixes https://github.com/mono/libgdiplus/issues/253
Relies on https://github.com/mono/libgdiplus/pull/278
> Fix GdipCreateBitmapFromFile for metafiles

- .gitignore
A DS_STORE file almost popped up in one of my commits so I added mac files to the gitignore
> Add mac gitignore

- src/matrix.c
- src/region.c
- tests/testregion.c
> Fix GetRegionBounds for large path regions

- src/region-bitmap.c
- src/region.c
No functional change, but helpful for the diffs in https://github.com/mono/libgdiplus/pull/280
> Cleanup region code to use switch statements

- src/graphics.c
- src/image.c
- src/region.h
- tests/testgraphics.c
Fixes #305
Fixes #306
Fixes #307 
Fixes #308
> Add graphics clip tests and fix region bugs

- src/font.c
- tests/testfont.c
- tests/testhelpers.h
Fixes https://github.com/mono/libgdiplus/issues/162
>  Fix font family not initialized in GdipCreateFontFromLogfont

- src/bmpcodec.c
- src/codecs.h
- src/emfcodec.c
- src/icocodec.c
- src/image.c
- src/jpegcodec.c
- src/pngcodec.c
- src/tiffcodec.c
- src/wmfcodec.c
- tests/.gitignore
- tests/Makefile.am
- tests/testcodecs.c
- tests/testhelpers.h
Fixes https://github.com/mono/libgdiplus/issues/382
Depends on https://github.com/mono/libgdiplus/pull/315
> Add ImageCodec tests

- src/matrix-private.h
- src/matrix.c
- src/matrix.h
> Fix the signatures of matrix functions

- src/region-bitmap.c
- src/region.c
- tests/testregion.c
Fixes part of #291
~Depends on #326~
~Depends on #311~
~Depends on #286~
~Depends on #293~
> Fix various region visibility edge cases

- tests/testregion.c
Separated from https://github.com/mono/libgdiplus/pull/280/commits
> Add more Region tests

- src/font-private.h
- src/font.c
- src/graphics-path.c
- src/text-pango-private.h
- src/text-pango.c
- tests/testfont.c
- tests/testgraphicspath.c
Fixes #321
Fixes #160 
~Relies on #227~
> Fix font em size

- .jenkins-windows.ps1
> Fix Windows build

- src/graphics-path-private.h
- src/graphics-path.c
- src/region.c
- tests/testregion.c
Should check for Ok, not !Ok
Fixes https://github.com/mono/libgdiplus/issues/399
Fixes https://github.com/mono/libgdiplus/issues/398
Contributes to https://github.com/mono/libgdiplus/issues/395
Contributes to #338
> Fix infinite path region calculations

- src/general.c
- src/graphics-path.c
- tests/testgraphicspath.c
- tests/testhelpers.h
> Fix GdipCreatePath2 validation and add tests

- src/pathgradientbrush.c
Fix PathGradientBrush transforms, and also gradient direction.
> PathGradientBrush fixes

- src/general-private.h
- src/matrix.c
- tests/testmatrix.c
Fixes https://github.com/mono/libgdiplus/issues/464
Fixes https://github.com/mono/libgdiplus/issues/463
> Add more Matrix tests and fix bugs

- src/hatchbrush.c
- src/hatchbrush.h
- tests/testhatchbrush.c
> Mathc GDI+ HatchBrush definitions

- src/general.c
- src/stringformat-private.h
- src/stringformat.c
- tests/testgeneral.c
- tests/teststringformat.c
Fixes https://github.com/mono/libgdiplus/issues/476
> Make generic string formats singletons

- src/pathgradientbrush.c
- src/pathgradientbrush.h
- tests/testpathgradientbrush.c
Fixes https://github.com/mono/libgdiplus/issues/468
Fixes https://github.com/mono/libgdiplus/issues/466
> Add more PathGradientBrush/SolidFill tests, cleanup the source code and fix compat bugs

- src/pen.c
- src/pen.h
- tests/testpen.c
Fixes https://github.com/mono/libgdiplus/issues/473
>  Add more Pen tests, fix bugs and cleanup the source

- src/graphics-path.c
- tests/testgraphicspath.c
Fixes https://github.com/mono/libgdiplus/issues/403
> Add GraphicsPath data retrieval tests and fix compat bugs

- .gitignore
- .travis.yml
- README.md
- configure.ac
Also add flags for `-g` and -`O1` which improve line numbers
> Make asan flags easier to add

- src/customlinecap.c
- src/customlinecap.h
- tests/testcustomlinecap.c
To match GDI+ and also some random code changes
> Fixup custom line cap definitions

- src/adjustablearrowcap.c
- src/adjustablearrowcap.h
- tests/testadjustablearrowcap.c
To match GDI+ and also some random code changes
> Fixup adjustable arrow cap definitions

- src/graphics-path.c
- src/graphics-path.h
- tests/testgraphicspath.c
Fixes https://github.com/mono/libgdiplus/issues/406
Fixes https://github.com/mono/libgdiplus/issues/407
Fixes https://github.com/mono/libgdiplus/issues/502
> Add tests for path manipulation and fix compat bugs

- src/gdipenums.h
- src/graphics-private.h
- src/graphics.c
- src/graphics.h
To match GDI+ (and so I can write some tests for these in the future)
> Cleanup Graphics container/state definitions

- src/graphics-path.c
- src/region.c
- tests/testregion.c
Fixes https://github.com/mono/libgdiplus/issues/336
>  Fix combine for negative rects/paths and IsEmpty

- src/brush-private.h
- src/solidbrush.c
- tests/testbrush.c
- tests/testhelpers.h
- tests/testsolidbrush.c
Fixes https://github.com/mono/libgdiplus/issues/499
/cc @filipnavara
> Fix SolidBrush alpha compositing mode bug

- src/region.c
- tests/testregion.c
Fixes #507 
Fixes #438 
Fixes #529
Fixes #528
Fixes #527
> Fix some region transform bugs

- src/graphics.c
- tests/testgraphics.c
Fixes https://github.com/mono/libgdiplus/issues/504
Fixes https://github.com/mono/libgdiplus/issues/505
Fixes https://github.com/mono/libgdiplus/issues/440
Fixes https://github.com/mono/libgdiplus/issues/439
Contributes to https://github.com/mono/libgdiplus/issues/309
> Fix results of GdipGetClipBounds after setting the clip

- src/matrix.c
GDI+ seems to map values between max(float) and infinity to max(float), instead of infinity. This is covered by a couple of tests in the corefx `MatrixTests` test suite.
This PR updates libgdiplus so that it matches the observed GDI+ behavior.
> Matrix: Handle boundary values

- src/bitmap.c
- tests/testbitmap.c
> Fix validation in GdipBitmapLockBits

- src/bitmap.c
> Cleanup some code in bitmap.c

- configure.ac
Let's get the static analyser stuff in, then this, and tag, and stuff
> Change to 6.0 for release. So many changes deserves a big number

- configure.ac
Since we made changes, cut a new release. Merge when happy with the underlying changes.
> Bump to 6.0.1

- src/lineargradientbrush.c
- tests/testlineargradientbrush.c
> Assign LinearGradientBrush to null if failed to create

- src/imageattributes.c
> Fix cut & paste error in gdip_process_bitmap_attributes

- src/bitmap.c
- src/bmpcodec.c
- src/graphics-path.c
- src/image.c
- src/metafile.c
- src/pngcodec.c
- src/region.c
These Resource Leaks were identified at https://scan.coverity.com/projects/libgdiplus
> Fixing Resource Leaks identified by Coverity Scan

- tests/Makefile.am
Fixes https://github.com/mono/libgdiplus/issues/620
> Update googletest to v1.10

- src/gifcodec.c
Co-authored-by: Alexander Köplinger
> Fix memory leaks in GIF codec error paths
