mono/libgdiplus

tests/Makefile.am
https://bugs.gentoo.org/367345
Signed-off-by: Justin Lecher <jlec@gentoo.org>
=> Add missing -lm for linking test detected by ld.gold

autogen.sh
Current Debian packaging puts libtool in its own package (libtool-bin)
leaving only libtoolize in the main package. The mono build process
uses libtoolize not libtool, so during autogen check for libtoolize
not libtool.
=> Check for libtoolize rather than libtool

configure.ac
The resulting string is later exported (as part of GDIPLUS_LIBS) to the
generated pkg-config file and this file shouldn't contain
-L${libjpeg_prefix}/lib -ljpeg as libjpeg_prefix is unknown in this context...
=> correctly resolve the variable of jpeg library prefix

configure.ac
This fixes build failures where the libjpeg/libtiff/libgif linking logic forces use of --prefix, which resolves to NONE - e.g. https://jenkins.mono-project.com/job/test-libgdiplus-mainline/22/label=ubuntu-1404-amd64/consoleFull
=> If the user doesn't mandate --prefix=, assume a value

configure.ac, src/gdiplus-private.h, src/general.c, src/graphics-private.h, src/graphics.c, tests/Makefile.am
X11 no longer ships with macOS, so building libgdiplus over there fails. This PR makes x11 integration optional, by adding a `--without-x11` flag.
This will also enable adoption of libgdiplus in homebrew.
Related issues: Homebrew/legacy-homebrew#45393, #13, #35
=> Support building on macOS with optional X11

src/pngcodec.c
Mono's System.Drawing currently does not support PNG images with 16 bits per pixel - in .NET, RGB colors are usually expressed as an 8-bit value.
Changes the call to png_read_png and passes PNG_TRANSFORM_STRIP_16, which reduces the color depth from 16 bit to 8 bit by dropping the last 8 bits - so you end up with a 24bpp instead of a 48bpp PNG image for RGB images and 32bpp instead of 64bpp for RGBA images.
Net impact is that the quality of the image is slightly reduced instead of refusing to process the image (and potentially crashing the application) altogether; proper support would mean supporting 16-bit color channels.
Partially fixes http://bugzilla.ximian.com/show_bug.cgi?id=80693
=> Support 48/64bpp PNG images

src/font.c, src/gdiplus-private.h, src/general-private.h, src/pngcodec.c, src/win32_io.c, src/win32_io.h
Enables building libgdiplus using Visual C++:
A couple of minor fixes which allow building libgdiplus natively on Visual C++ (Windows)]
- use `tmpfile` instead of `mkstemp` to get generate a temporary file
- Define `_USE_MATH_DEFINES` so `M_PI` is defined
- Don't `#include` Unix-only headers
- Don't redefine `max` and `min`
- Fix macro expansion
=> Visual C++ compatibility fixes

src/bitmap.c, src/dstream.c, src/dstream.h, src/metafile.c
`sizeof(void*)` is defined by gcc only, and Visual C++ will not let you increment the value of `void*`-typed pointers. To enable compilation with Visual C++, use the underlying data type - which is `BYTE *`.
=> Visual C++ Compatibility: Use BYTE* instead of void*

src/bitmap.c
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=44127.
=> Preserve bitmap resolution values for clones

src/pngcodec.c
This fixes a problem introduced by 5ed200d5d73edc54969b34c708d18728d38c070b.
=> Do not zero RGB pixels if A == 0

src/hatchbrush-private.h, src/hatchbrush.c
if use a brush HatchBrush with a transparent background that background was not transparent
After
=> support RGBA in HatchBrush

.gitignore, appveyor.yml, libgdiplus.sln, src/libgdiplus.vcxproj, src/packages.config
This completes the initial work to get libgdiplus compiling with Visual C++ and running on Windows.
Adds a Visual C++ project (and VS solution) which compiles libgdiplus. Most of the dependencies are sourced from HexChat's gtk-win32; others come from CoApp packages on NuGet.
=> Add Visual C++ project, AppVeyor script

configure.ac
Otherwise, weird side-effects can occur, such as libgdiplus
linking to multiple png versions, when e.g. png-1.6 and png-1.2 are
both available.
Ultimately this should be fixed more generic and use something like `PKG_CHECK_MODULES([PNG], [libpng >= 1.6])`, picking the _latest_ libpng always. Also see the [pkg-config manpage](https://linux.die.net/man/1/pkg-config) explaining those proper macros. For now, I just kept the logic.
=> Include pkg-config check for libpng16

src/font.c, tests/.gitignore, tests/Makefile.am, tests/testfont.c
This fixes the following C# tests (see https://github.com/dotnet/corefx/pull/21552)
```cs
[Fact]
public void AddMemoryFont_ZeroMemory_ThrowsArgumentException()
{
using (var fontCollection = new PrivateFontCollection())
{
AssertExtensions.Throws<ArgumentException>(null, () => fontCollection.AddMemoryFont(IntPtr.Zero, 100));
}
}
[Theory]
[InlineData(0)]
[InlineData(-1)]
public void AddMemoryFont_InvalidLength_ThrowsArgumentException(int length)
{
using (var fontCollection = new PrivateFontCollection())
{
byte[] data = File.ReadAllBytes(Helpers.GetTestBitmapPath("CodeNewRoman.otf"));
IntPtr fontBuffer = Marshal.AllocCoTaskMem(data.Length);
try
{
Marshal.Copy(data, 0, fontBuffer, data.Length);
AssertExtensions.Throws<ArgumentException>(null, () => fontCollection.AddMemoryFont(fontBuffer, …
```
=> Fix null pointer dereference in GdipPrivateAddMemoryFont

src/jpegcodec.c, src/libgdiplus.vcxproj, src/pngcodec.c, src/win32_io.c
@qmfrederik 
> libgdiplus\src\pngcodec.c(384): warning C4047: '=': 'unsigned char' differs in levels of indirection from 'png_bytep'
> libgdiplus\src\pngcodec.c(373): warning C4047: 'initializing': 'png_bytep' differs in levels of indirection from 'png_byte'
> libgdiplus\src\jpegcodec.c(591): warning C4133: '=': incompatible types - from 'BOOL (__cdecl *)(j_decompress_ptr)' to 'boolean (__cdecl *)(j_decompress_ptr)'
> libgdiplus\src\jpegcodec.c(628): warning C4133: '=': incompatible types - from 'BOOL (__cdecl *)(j_decompress_ptr)' to 'boolean (__cdecl *)(j_decompress_ptr)'
> libgdiplus\src\jpegcodec.c(706): warning C4133: '=': incompatible types - from 'BOOL (__cdecl *)(j_compress_ptr)' to 'boolean (__cdecl *)(j_compress_ptr)'
> LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with …
=> Fix MSVC warnings

src/GdiPlusFlat.h, src/lineargradientbrush.c, src/lineargradientbrush.h, src/pathgradientbrush.c, src/pathgradientbrush.h
These are all present on Windows, but missing in libgdiplus.
=> Fix missing APIs in GdiPlusFlat.h

src/win32structs.h
This causes some of the unit tests to fail to compile on Windows:
> c:\users\hugh\documents\github\libgdiplus\src\win32structs.h(129): error C2371: 'TCHAR': redefinition; different basic types
> c:\program files (x86)\windows kits\10\include\10.0.15063.0\ucrt\tchar.h(180): note: see declaration of 'TCHAR'
=> Fix redefinition of non-GDI Windows basic types in win32structs.h

src/texturebrush.c, tests/.gitignore, tests/Makefile.am, tests/testhelpers.h, tests/testtexturebrush.c
Add TextureBrush tests and fix a compat bug
=> Add TextureBrush tests and fix a compat bug

Makefile.am, src/Makefile.am, src/gdiplus-private.h, src/general.c, src/general.h, src/gifcodec.c, src/jpegcodec.c, src/libgdiplus.vcxproj, src/pngcodec.c, src/tiffcodec.c, winconfig.h.in
/cc @qmfrederik for feedback
This would simply return the libgdiplus version (e.g. `5.6`) as a string. It could be used like this:
```csharp
[DllImport("gdiplus")]
extern static string GetLibgdiplusVersion ();
Version LibgdiplusVersion {
get {
try {
return new Version (GetLibgdiplusVersion ());
} catch (EntryPointNotFoundException) {
return null;  // in case of older libgdiplus or Windows GDI+
}
}
}
```
not sure if the string version is the best option or we should return major+minor as an int? or some other counter?
=> [RFC] Add API for getting libgdiplus version

src/lineargradientbrush.c, src/pathgradientbrush.c, src/texturebrush.c, tests/testhelpers.h, tests/testlineargradientbrush.c, tests/testpathgradientbrush.c, tests/testpen.c, tests/testtexturebrush.c
Now matches Windows behaviour. The problem was that invalid MatrixOrder values could cause access to uninitialised memory - which is garbage data
=> Fix UB in various multiply transforms for pens/brushes

src/graphics-private.h, src/graphics.c, tests/testgraphics.c
Although this increases compat with GDI+, we’re backing this out because this is undefined behaviour.
See https://github.com/mono/libgdiplus/pull/95#discussion_r141030353
=> Revert checks for if graphics are deleted

tests/testadjustablearrowcap.c, tests/testbrush.c, tests/testclip.c, tests/testfont.c, tests/testgdi.c, tests/testgraphics.c, tests/testhatchbrush.c, tests/testhelpers.h, tests/testlineargradientbrush.c, tests/testmatrix.c, tests/testpathgradientbrush.c, tests/testpen.c, tests/testpng.c, tests/testreversepath.c, tests/testsolidbrush.c, tests/testtexturebrush.c
The first commit deals with test compilation failures running the tests against GDI+.
The main bulk of this PR is in the 3rd commit, which defines better error messages instead of the default message that doesn’t show much information.
=> Define custom assertions with better error messages

src/bitmap.c, src/lineargradientbrush.c, src/pathgradientbrush.c, src/pen.c
The Clang static analyzer sometimes complains for these patterns (but not all, for some reason).
I fixed a bunch of them by searching for `_new`
=> Add some missing status checks

configure.ac, src/carbon-private.c, src/carbon-private.h, src/metafile.c, src/win32structs.h
These I believe are set to the default with CMake (maybe not pedantic).
=> Enable extra warnings

src/pathgradientbrush.c, tests/testpathgradientbrush.c
Some of these are GDI+ bugs that we don’t want to replicate.
The other bug is that libgdiplus has a non-empty list of preset blends when it was created.
=> Fix some PathGradientBrush combat bugs/tests

src/image.c, src/metafile.c, tests/testgpimage.c, tests/testhelpers.h
Previously this wasn’t being set when we cloned the metafile.
=> Fix cloned metafile raw format

src/image.c, src/metafile-private.h, src/metafile.c, tests/testgpimage.c
Relies on #120
Previously, we’d be off by a factor of about 0.02-0.05.
I looked at the docs and discovered that GdipGetImageDimension for metafiles basically returns the width and height in 0.01 millimetre units.
So to get the dimensions, we can just convert the pixels into millimetres using the DPI, and then multiply that by 100 to get the right units.
This is now exactly the value that GDI+ returns, so we don’t need to nerf the tests for this behaviour difference. I’ve updated the tests to reflect the exact values returned by GDI+, that are now also returns by libgdiplus
=> Fix GdipGetImageDimension for metafiles to match GDI+

src/bitmap.c, src/dstream.c, src/font.c, src/graphics-path.c, src/image.c, src/lineargradientbrush.c, src/metafile.c, src/pathgradientbrush.c, src/pen.c
More occurrences of GdipAlloc without a check after
Some of these can be triggered with invalid data (e.g. in the headers of bitmaps) but others are rare cases. Still good to be careful though
=> Handle more allocation failures across the codebase

src/bmpcodec.h, src/gdipenums.h, src/win32structs.h
These are exposed in GDI+ on Windows, but not in libgdiplus.
This is necessary for some tests that I’m working on - I don’t have time rn to send those in so I’m just sending this PR in so the future one is easier to review with less code moving around.
=> Make some definitions public that are needed

tests/testbmpcodec.c, tests/testicocodec.c
For readability, consistency and to make the name of the test function actually make sense
Also adds some more negative tests for parsing BITMAPFILEHEADER
=> Cleanup codec tests

tests/testbits.c
Found running libgdiplus tests with asan
Also removes uncompilable and commented out code.
=> Fix testbits.c heap buffer overflow

src/bmpcodec.c, tests/testbmpcodec.c
If an OS/2 image was provided, we’d keep decoding as if the image header contained compression, height etc. etc.
But we should bail out early if we have parsed an OS/2 format
=> Add bitmap 1bpp tests and fix decoding OS/2 bitmaps

src/metafile.c, src/wmfcodec.c, src/wmfcodec.h
* Added a new drawing instruction / record (METAFILE_RECORD_DIBSTRETCHBLT) which is substantially the same as METAFILE_RECORD_STRETCHDIBITS
* Corrected parsing of certain values so that they're treated as signed instead of unsigned, including adding a GETS macro to complement the existing GETW but returning a SHORT instead of a WORD
* Fixed scaling for drawing to a specified size and improved translation at the same time
* Corrected handling of the DIB BitmapInfoHandler ImageSize field -- it now calculates the value when compression is not used (Compression field = 0 / RGB)
_Note:_ these are the extracted WMF changes from https://github.com/mono/libgdiplus/pull/28 + cleanup, let's see what CI says 😄
=> Fixed issues that prevented visibly drawing many WMF files

tests/testbmpcodec.c, tests/testgifcodec.c, tests/testhelpers.h, tests/testicocodec.c
Saves duplicated code (and will be used in tiff/png/jpeg/wmf/emf stuff in the future)
=> Add a helper for deleting a file

tests/testgifcodec.c, tests/testgpimage.c, tests/testhelpers.h, tests/testmetafile.c, tests/testtiffcodec.c
Before there would be no line number for the actual data that caused the verification to fail
We can fix this by turning the function into a macro
Relies on #147
=> Make image verification failures easier to spot

src/font.c, src/win32_io.c, src/win32_io.h
write(3) doesn't accept a FILE* pointer masquerading as an int
=> Fix crash in GdipPrivateAddMemoryFont on Windows

src/metafile.c
Fixes #211
For the following data:
```
BYTE rectangle[] = {
/* -- Placeable Header -- */
/* Key */          0xD7, 0xCD, 0xC6, 0x9A,
/* Hmf */          0x00, 0x00,
/* Bounding Box */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x00, 0x0F,
/* Inch */         0xA0, 0x05,
/* Reserved */     0x00, 0x00, 0x00, 0x00,
/* Checksum */     0xB1, 0x52,
/* -- Metafile Header -- */ 
/* File Type */       0x01, 0x00,
/* Header Size */     0x09, 0x00,
/* Version */         0x00, 0x03,
/* Total Size */      0x09 + 0x07 + 0x07 + 0x03, 0x00, 0x00, 0x00,
/* Number Objects */  0x00, 0x00,
/* Max Record Size */ 0x08, 0x00, 0x00, 0x00,
/* No Parameters */   0x00, 0x00,
/* -- META_RECTANGLE -- */
/* Size */       0x07, 0x00, 0x00, 0x00,
/* Function */   0x1B, 0x04,
/* BottomRect */ 0x00, 0x08,
/* RightRect */  0x00, …
```
=> Update metafile defaults

src/font.c, src/general.c, src/win32-private.c, src/win32-private.h
A more sensible version of https://github.com/mono/libgdiplus/pull/228.
=> Implement gdip_get_display_dpi on Windows using older Win32 API.

src/bitmap.c
=> Do not ignore the offset parameter in gdip_property_get_*, it is used in TIFF code.

src/win32-private.c, tests/testhelpers.h
- Font files are binary so don't corrupt them in fopen
- The type of WCHAR * is guint32, not wchar_t on Windows libgdiplus.
=> Fix font behaviour on Windows

src/graphics-path.c, src/text-pango-private.h, src/text-pango.c
There are two code path where we need to do some custom text alignment outside of the `pango_layout_*` functions:
- Line alignment (vertical alignment when the text is rendered in horizontal direction)
- Alignment in conjunction with no-wrap flag, which is not directly supported by Pango
In both cases it is necessary to add the computed alignment offset before doing the actual rendering with `pango_cairo_show_layout`. This wasn't done before, so DrawString effectively ignored StringFormat->LineAlignment.
=> Fix DrawString alignment with pango text rendering.

src/graphics.c, src/region-bitmap.c, tests/testclip.c
- Possible fix for https://github.com/dotnet/corefx/issues/27320.
- Needs unit tests.
- The metafile code doesn't make sense, I am aware of that. It is copied from `GdipSetClipRegion` and the `metafile_SetClip*` functions are not implemented anyway.
=> Transform path in GdipSetClipPath by clip_matrix if necessary.

src/font-private.h, src/font.c, tests/testfont.c
The loading of custom fonts with Cairo was broken since Cairo never received the font file name. It performed substitution and ended up using a different font (Tahoma or Verdana). Also fixes the unit test to use actual Code New Roman metrics, which were verified on Windows.
=> Fix loading custom fonts

src/font-private.h, src/font.c, src/fontcollection-private.h, src/fontfamily-private.h, src/general.c, src/text-pango.c
Fixes issue #237.
Pango has three backends - CoreText, Win32 and FontConfig. By default it tries to select the one that is most appropriate for the platform. However the current libgdiplus code depends on FontConfig and FreeType directly, so we need to force the use of FontConfig backend. Additionally it fixes an issue with custom fonts, which use custom FcConfig objects that were not properly propagated to Pango. Lastly, it fixes a memory leak in gdip_get_fontfamily_details.
=> Use our own pango font maps to support custom fonts and use FontConfig backend on macOS by default

src/metafile.c
Example bytes: 
```cpp
BYTE rectangleWithCustomBrush[] = {
/* -- Placeable Header -- */
/* Key */          0xD7, 0xCD, 0xC6, 0x9A,
/* Hmf */          0x00, 0x00,
/* Bounding Box */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x00, 0x0F,
/* Inch */         0xA0, 0x05,
/* Reserved */     0x00, 0x00, 0x00, 0x00,
/* Checksum */     0xB1, 0x52,
/* -- Metafile Header -- */ 
/* File Type */       0x01, 0x00,
/* Header Size */     0x09, 0x00,
/* Version */         0x00, 0x03,
/* Total Size */      0x09 + 0x08 + 0x04 + 0x07 + 0x04 + 0x07 + 0x03, 0x00, 0x00, 0x00,
/* Number Objects */  0x02, 0x00,
/* Max Record Size */ 0x08, 0x00, 0x00, 0x00,
/* No Parameters */   0x00, 0x00,
/* -- META_CREATEPENINDIRECT -- */
/* Size */      0x08, 0x00, 0x00, 0x00,
/* Function */  0xFA, 0x02,
/* Pen Style */ 0x00, 0x00, …
```
=> Don't listen to PS_JOIN_MASK in createPen

.gitattributes
`alpha-premul-table.inc` is classified as PHP, that amounts to 13.4% of the code:
With this override, linguist will classify the inc file as C.
Related issue https://github.com/github/linguist/issues/4082.
=> Override inc language classification

src/libgdiplus.vcxproj, src/packages.config
I don't really understand why we need the FreeRasterBitsMono workaround. The problem is that we crash calling DGifCloseFile when freeing `RasterBits`.
For some reason, freeing it manually works. This might need more investigation, but I'm at a loss here
Fixes #194
=> Support giflib on Windows

src/text-pango.c, tests/Makefile.am, tests/testtext.c
Unfortunately the Cairo text backend is too broken for the tests to be enabled there, so I initially enable them only when Pango text backend is used. Even now some of the tests are disabled because of small issues in the Pango code.
=> Add initial tests for GdipMeasureString and fix Pango text backend to pass them

src/region.c, tests/testregion.c
Found when running the region tests against Windows GDI+
=> Fix GdipIsRegionEmpty for negative rects

src/metafile.c
For EMF files the mode is `MM_TEXT`, not `MM_TWIPS`
=> Use the default map mode for playing EMF metafiles

src/text-cairo.c, src/text-pango.c, tests/testtext.c
Tests and fixes part of behaviour changed by PR #137.
=> Initial test and fixes for GdipMeasureCharacterRanges

src/bmpcodec.c, tests/testbmpcodec.c
Fixes #302
Relies on https://github.com/mono/libgdiplus/pull/318
Relies on https://github.com/mono/libgdiplus/pull/303
=>  Fix decoding bitmaps with overly large palettes

src/general-private.h, src/general.c, src/lineargradientbrush.c, src/pathgradientbrush.c, tests/testhelpers.h, tests/testlineargradientbrush.c, tests/testpathgradientbrush.c
- Handle memory allocation failures better
- Implement GdipCreatePathGradientI in terms of GdipCreatePathGradient
- Add more tests
- Fix ordering of parameter validation to match GDI+
- Fix writing to positions when the blend count is 1, to match GDI+
=> Cleanup PathGradientBrush code and fix some compat bugs

configure.ac
Tested with a mix of AIX Toolbox and Perzl packages. Builds a 64
bit libgdiplus to go with mono.
X11, giflib (but not ungiflib), libexif, libpng, giflib, and libtiff
are all used.
Due to deficiencies in the AIX Toolbox version of Cairo, where it
specifies system X11 in the package, but IBM's system X11 lacks
a package, you must specify Cairo flags manually to the configure
script like so. This isn't done by the script as you may be using
a Cairo linked against a newer X.org instead.
```shell
CAIRO_CFLAGS=-I/opt/freeware/include/cairo
CAIRO_LIBS="-L/opt/freeware/lib -lcairo"
CPPFLAGS=-I/opt/freeware/include/cairo
```
This is untested on PASE.
=> Initial AIX support for libgdiplus

src/bitmap.c, src/bmpcodec.c, src/bmpcodec.h, tests/testbmpcodec.c
Fixes https://github.com/mono/libgdiplus/issues/189
Fixes https://github.com/mono/libgdiplus/issues/157
=> Fix bmpcodec 16bpp decoding

src/general-private.h, src/general.c, src/graphics-cairo-private.h, src/graphics-cairo.c, src/graphics-metafile-private.h, src/graphics-metafile.c, src/graphics.c
- We can implement `Gdip{Draw/Fill}*I` functions in terms of `Gdip{Draw/Fill}`
- We can implement some single functions in terms of multiple functions (e.g.`Gdip{Draw/Fill}Rectangle` in terms of `Gdip{Draw/Fille}Rectangles`
This will also make it a lot easier to record data when metafile recording is implemented, as EMF+ records are only for the float/array versions of GDI+ draw/fill functions
=> Cleanup graphics draw/fill functions to avoid code duplication

src/graphics-cairo.c, src/region-bitmap.c, src/region-bitmap.h, tests/testgraphics.c
This is alternative patch to #283 for issue #195. It reduces memory allocations and moves the hard part of rendering to Cairo.
=> Use native cairo functions for rendering region mask bitmaps.

src/customlinecap.c, src/graphics-cairo.c, src/graphics-path-private.h, src/graphics-path.c, src/graphics-pathiterator.c, src/pathgradientbrush.c, src/region-bitmap.c, src/region-path-tree.c, tests/.gitignore, tests/Makefile.am, tests/testgraphicspath.c
* Fixes issues #223, #224 and #225.
* Introduces out of memory checks for the path APIs.
* Optimises lot of the APIs to prevent unnecessary allocations, frees and copying.
=> Rewritten memory management of GpPath objects

src/region-private.h, src/region.c, tests/testregion.c
~Depends on #327 which depends on #326 which depends on #286~
I’ve implemented this pr for several reasons:
On its own this PR slightly increases compatibility with GDI+ as infinite regions are encoded in the data as a type of 0x10000003 instead of a type 0x10000001 and a rectangle with infinite size.
However, this now allows us to differentiate between infinite and non-infinite regions which, in a future PR will be used to increase the compatability with GdipGetRegionData even more
The cost of creating a `new Region()` is now cheaper and avoids allocations by creating an infinite rect and putting it in an array.
In the future this flag can easily be used in other settings to increase performance
Fixes #391
Fixes #335
Fixes #337
Fixes #341
Fixes #343
Fixes #344
Fixes #350
Fixes #353
Fixes …
=> Actually implement RegionTypeInfinite

src/graphics-path.c, tests/testgraphicspath.c, tests/testhelpers.h
- When using the Pango text backend, pass an actual GpGraphics object.
- For GdipAddPathString, use an infinite Cairo Recording surface. I was having problems with longer strings clipping on the old 1x1 image surface.
- In GdipAddPathString, fix checking whether the next path point is a CAIRO_PATH_CLOSE_PATH.
- Also change append to correctly handle the second of two identically-positioned points closing the path.
=> GraphicsPath fixes

src/font.c, src/text-pango.c, tests/testtext.c
Some updates to the Pango text backend. The commit messages should be adequate explanation, but if they're not just ask.
=> Pango fixes

src/graphics-cairo.c
The old is giving `cairo_curve_to` the origin point and then two control points, with no destination. It needs the two control points and the destination, with the origin being specified by the earlier call to `cairo_move_to`.
=> Fix drawing bezier curves.

src/region.c, tests/testregion.c
Region Union was sometimes doing strange things. The problem seems to be that gdip_intersects was returning true in some situations for rectangles that do not necessarily intersect (right of first == X of next, irrespective of Y / Height). I have added a test-case for this.
I initially made gdip_intersects return true for any rectangles that touch, as this would seem to be the desired behaviour for unions. However, that caused test failures for XOR which traces back to exclude, so I tried changing back to only returning true when actually overlapping. That in turn caused test failures for union, so I added a parameter to choose which behaviour was desired.
=> Region fixes

src/graphics-private.h, src/graphics.c, src/image.c, tests/testgraphics.c
Fix setting the world transform when in a container. It needs to take the parent transform into account.
Also store and use the original GpGraphics bounds, to fix the action of `apply_world_to_bounds` (was applying the complete transform to partially-transformed coordinates.
=> Transform fixes

src/graphics.c
Taking the address of an array then converting it to a pointer is incorrect.
- not sure why this code actually works though, maybe because PointF the same size as a pointer?
And remove unecessary checks for status
- there's no way GdipTransformMatrixPoints can fail here and no one even checks the return value anyway
=> Fix incorrect cast in apply_world_to_bounds

src/graphics-path.c, src/region.c, tests/testregion.c
The failure in the tests was due to a PR that fixed the behaviour of `GdipTransformRegion` that we didn't account for when normalizing things
/cc @akoeplinger
=> Reapply "Fix combine for negative rects/paths and IsEmpty"

configure.ac, src/gdiplus-private.h, src/general.c, src/graphics-private.h, src/graphics.c, tests/Makefile.am
All other libraries in libgdiplus follow the schema of defining (or not) a definition (e.g. `HAVE_LIBJPEG`)
However, the one for x11 is inconsistent, as it is either 1 or 0 and is called `HAS_X11`.
- Rename this to `HAVE_X11`
- Change it to be defined or not, rather than 1 or 0
=> Update definition for X11 definition in config.

src/bitmap-private.h, src/bitmap.c, src/bmpcodec.c, src/bmpcodec.h, src/icocodec.c, src/win32structs.h
Aims:
- Make it simpler to read this 1000 line long function
- Make it clearer what we're doing
There are a number of discrete stages involved in decoding a bmp image
- Reading the header
- Reading the palette if any
- Calculating the stride
- Reading the scans
- Converting the scans to a target pixel format if necessary
This PR splits the core bmp decoding into several routines that clarify these stages and will make it easier for me to make future changes
=> Refactor bmpcodec

configure.ac
=> fix libm not getting used when building

src/graphics-pathiterator.h
These methods were not being exported on Windows.
=> Add missing WINGDIPAPI annotation to graphics path iterator methods

configure.ac
These flags were added [quite some time ago](https://github.com/mono/libgdiplus/commit/bce17c28c445c49e9349aace2eb0e4a9bd235aad).
It is not entirely clear why they were needed since the original bug report is not easily accessible.
`-no-cpp-precomp` either [does nothing or causes errors](http://www.mistys-internet.website/blog/blog/2013/10/20/no-cpp-precomp-the-compiler-flag-that-time-forgot/).
`-flat_namespace -undefined suppress` is not a standard practice and causes [problems that are difficult to track down](https://trac.macports.org/ticket/24501).
=> Avoid unnecessary/dangerous compatibility flags on macOS

src/bitmap.c
Fixes https://github.com/mono/libgdiplus/issues/443
The condition is simplified with the cast to `UINT`, as it reduces the branches in the method.
=> GdipBitmapSetPixel correct bounds-check

src/font.c, src/general-private.h, src/general.c, src/graphics-path.c, src/image.c, src/imageattributes.c, src/metafile.c, src/text-cairo.c, src/text-pango.c
This patch allows Garphics.MeasureString() and Graphics.DrawString() to correctly measure and draw unicode characters with a codepoint greater than 0xffff.
=> Add support for utf16 high/low surrogates in measurestring/drawstring.

src/customlinecap.c, src/general.c, src/graphics-cairo.c, src/graphics-private.h, src/graphics.c, src/image.c, src/pen.c, tests/testclip.c, tests/testgraphics.c
Fixes #545. Also fixes a typo in cairo_SetWorldTransform where input 'matrix' argument was not used.
=> Respect page units when current transformation matrix is passed to cairo

src/graphics-cairo.c, tests/testclip.c
Fixes #547, fixes #552. Clipping of paths and path-based regions was broken in
5dd3b5da1565a99912ff8570054dad26a04e9c08 (NULL matrix is not accepted in GdipGetRegionScans and GdipGetRegionScansCount).
=> Fix clipping of non-rectangular paths

src/imageattributes.c
`GdipCloneImageAttributes` would do a `memcpy` of the `ImageAttributes` class, but did not do deep cloning of reference values. This leads to double frees (and other erratic behavior) when disposing the original `GpImageAttributes` and its clone.
=> Implement deep cloning of ImageAttributes

src/bitmap.c
Simlar to #557, assuming a `HICON` is a `GpImage` will very likely not work on Windows; so just return `NotImplemented` instead of risking taking down the entire process.
Simlar to #557, the corefx unit tests will call this with HICON set to a value of `0xa` (i.e. an invalid pointer), not sure how we can validate that pointer short of tracking all `GpGraphics` objects.
=> Don't implement GdipCreateBitmapFromHICON on Windows

src/graphics.c
The first thing `GdipCreateFromHdc` does, is to cast this from `HDC` to `GpGraphics`.  This is almost guaranteed to fail on Windows, and even something as simple as `clone->type` will cause an access violation.
Instead, just return `NotImplemented` when compiled for Win32.
A more robust strategy may be to keep track of all `GpGraphics` objects we allocate, and check whether `hdc` points to any of those, before casting `hdc` to `GpGraphics`.
=> Don't attempt to implement GdipCreateFromHDC on Windows

src/bitmap.c
If you create a new bitmap from scratch (that is, `scan0` is `NULL`), `GdipCreateBitmapFromScan0` will allocate memory to hold the raw bitmap data for you.
It then attempts to initialize this. By default, it will `memset` all bytes to 0, so you should get a black image in most formats. However, for formats with alpha-channels, this would set alpha to `0`, causing the image to be "completely translucent black" (AKA white).
So the method goes on a quest to set the alpha channel to 1. It iterates over the framebuffer using a 32-bit `ARGB` value. For pixel formats with < 32 bpp, this would cause a buffer overflow for the last pixel.
Fix the check for the bpp, and make sure we really have a 32bpp pixel format.
=> GdipCreateBitmapFromScan0: Fix a buffer overflow with pixel formats < 32 bpp

src/lineargradientbrush.c
A gradient on from point A to itself doesn't make much sense, and GDI+ returns OOM. Make libgdiplus do the same thing.
This is covered by the corefx `LinearGradientBrushTests.Ctor_EqualPoints_ThrowsOutOfMemoryException` test.
=> Return OutOfMemory for 0-length gradient brushes

src/graphics-path.c
Align with GDI+.
Covered by `GraphicsPathTests.AddArc_ZeroWidthHeight_ThrowsArgumentException` and `GraphicsPathTests.AddPie_ZeroWidthHeight_ThrowsArgumentException` in corefx
=> Graphics Path: Reject Arcs and Pies with width or heigth of zero

src/region.c
`GdipGetRegionScans` transforms `region` and stores the result in `work`.  From that point on, all work is done on `work` and no longer on region.
However, there still was a switch on `region->type` instead of `work->type` which would send `GdipGetRegionScans` down the wrong path if the type has changed.
To make things worse, `gdip_region_convert_to_path` changes the `type` and clears `rects`, but did not reset `cnt` to 0.
`RegionTests.GetRegionScans_CustomMatrix_TransformsRegionScans` in the corefx test suite could trigger this.
=> GdipGetRegionScans: Avoid segfault, use work instead of region

src/text-cairo.c
Having this hooked up allows for better rendering for two/three color displays.
The text geometry isn't identical to Windows, but the aliasing is very similar, at least on Ubuntu running under the WSL. Note that CAIRO_ANTIALIAS_GRAY still generates non-gray pixels on Raspbian on RPi3B+. Presumably an issue with Cairo itself?
I've included the results of running the code in #535 on Ubuntu.
**Before**
**After**
Fixes #535
=> Add text mode settings

src/gifcodec.c
It was removed upstream so we need to include a copy of it.
The upstream code is licensed as MIT.
Fixes https://github.com/mono/libgdiplus/issues/546
=> gifcodec.c: Include copy of GifQuantizeBuffer function from giflib

src/general.c
fontconfig will not enumerate _any_ fonts if it cannot find a configuration file.
This PR tries to set some sensible defaults in that scenario, so that at least the system-wide fonts can be found.
=> font-config: Use a rudimentary default configuration when no config file can be found

src/graphics.c
The current implementation of `GdipSaveGraphics` would set `GraphicsState` to the zero-based index of the current state in an array. The Windows implementation of System.Drawing [asserts that `GraphicsState` is non-zero](https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/Graphics.Windows.cs#L2690).
So simply increment `GraphicsState` by one when setting it, and substract one when reading it.
=> Keep GraphicsContainer/GraphicsState non-zero

src/customlinecap.c, tests/testcustomlinecap.c
Only a couple of `LineCap` values are accepted by GDI+. All other values are ignored, and silently reset to `LineCapFlat`.
This behavior is covered by the `CustomLineCapTests` tests in corefx.
=> CustomLineCap: Better argument validation

src/adjustablearrowcap.c, src/bitmap.c, src/bmpcodec.c, src/customlinecap.c, src/gifcodec.c, src/graphics.c, src/icocodec.c, src/image.c, src/pngcodec.c, src/region-bitmap.c, src/tiffcodec.c
Various instances of "Multiplication result may overflow 'unsigned int' before it is converted to 'size_t'." and "comparison is always the same" warnings.
=> Fix a couple static analyzer warnings

src/lineargradientbrush.c, src/pathgradientbrush.c
We'd allocate memory in `gdip_linear_gradient_new` and then override it immediately. Avoid allocating by just calling GdipAlloc instead of that method
=> Fix memory leaks cloning Path/Line gradient brushes

src/pen.c
- When overriding the brush, dispose of it if we own it
- When setting the new brush, we actually own it, so want to dispose it when we dispose the pen
=> Fix leak in GdipSetPenColor

src/imageattributes.c, tests/testimageattributes.c
Regression from https://github.com/mono/libgdiplus/pull/560
/cc @qmfrederik
=> Fix ImageAttributes clone crash with color profile names

autogen.sh, configure.ac, tests/Makefile.am
```In file included from jpegcodec.c:40:
In file included from /usr/local/include/jpeglib.h:27:
/usr/local/include/jmorecfg.h:199:24: warning: redefinition of typedef 'UINT16'
is a C11 feature [-Wtypedef-redefinition]
typedef unsigned short UINT16;
^
./win32structs.h:347:17: note: previous definition is here
typedef guint16 UINT16;
```
=> Fix warnings running autogen.sh

src/jpegcodec.c
Fetch the X and Y pixel density from the EXIF data if the they could not be retrieved from the JPEG metadata.
Fixes #539
=> Read the X and Y pixel density from EXIF data

src/jpegcodec.c
If `image->active_bitmap->pixel_format` is not a valid pixel format, the call to `goto error` would cause a call to `jpeg_destroy_compress` which would access `cinfo.mem`. Initialize it to `NULL` to avoid an AV.
=> JPEG codec: initialize cinfo.mem

src/bitmap.c
…to fix possible inconsistencies for drawing flipped images.
There were few usages of `gdip_bitmap_clone` with missing flush calls. Unfortunately there is zero code coverage for these paths. The chances of actually turning this into visible bug are thin. One would have to create an ARGB32 bitmap, draw into it and then try to paint it flipped into another bitmap. Adding the flush call down the stack is a safety precaution that should prevent any incorrect usage.
=> Add bitmap flushing to gdip_bitmap_clone

src/image.c
While image rotating, surface existance and premultiplication format should be checked. In first case, surface should be usea as a source for rotting. In other case - old behaviour. See: bitmap.c@GdipBitmapGetPixel
In the end of function old surface should be replaced to new one.
This opened task described problem and the way to reproduce:
https://github.com/mono/mono/issues/17743
=> Use surface instead of scan0 while image rotation if it is not empty

src/bitmap.c, src/graphics.c, src/image.c
`gdip_bitmap_dispose` was leaking the bitmap backing data for certain image formats. This is essentially the same issue as in https://github.com/mono/libgdiplus/commit/1afe4711f10bd52e14a4c7985eae7414eda4108c but on a different place. I now unified both of the places to use the same code.
=> Fix multiple memory leaks for GpBitmap image data

src/bitmap.c, src/graphics.c, src/image.c
* Fix multiple memory leaks for GpBitmap image data.
* Fix memory leak in GdipSetClipRect
`gdip_bitmap_dispose` was leaking the bitmap backing data for certain image formats. This is essentially the same issue as in 1afe471 but on a different place. I now unified both of the places to use the same code.
=> Backport of memory leak fixes (#635) to 6.0 branch

src/text-cairo.c
This PR fix an issue where Japanese characters are recognized as spaces. (#627)
This fix does not recur issue (https://github.com/mono/mono/issues/8272) fixed by #370.
=> Fix: an issue where Japanese characters are recognized as spaces

src/pen.c
First, base the 1px minimum line width on output line width, not pen width. If scaling up with a pen width < 1, the output width may well be more than 1px, in which case the correct output is that width, not 1px.
Second, `cairo_device_to_user_distance()` can provide negative values. Use the absolute value of its outputs. The negative comes from mirror-type transforms (negative scale values). Using a negative value results in no line being drawn; and if dash_count > 0, also an error from Cairo.
Third, use the maximum of `widthx` and `widthy`, because scaling is not necessarily uniform. Setting a minimum line width is only necessary because Cairo produces dashed lines when scaling up and the output width is < 1px, and we don't want that happening when scaling Y more than X.
=> Fix some pen width problems

src/imageattributes.c
Fixes https://github.com/mono/mono/issues/8514
=> Fix comparison for color keying when applying image attributes

src/graphics.c
Fixing an issue with the state count not being decremented (stack not popped) when EndContainer is called. This would cause a System.OutOfMemoryException when 512 calls to BeginContainer were made since application start.
=> Fix System.OutOfMemoryException when 512 calls to BeginContainer were made since application start

src/pen.c
Fix double free crash if you assign a custom dash array then switch back to a standard pattern.
=> Fix double free SIGABRT with custom dash array handling

src/pen.c
This fixes part of #647 that I complained about in comment.
I tested locally that Windows libgdiplus in fact resets the dash array on `DashStyleCustom` -> `DashStyleDashDot` -> `DashStyleCustom` transition done using `GdipSetPenDashStyle`. Following this transition `GdipGetPenDashArray` returns the Dash-Dot pattern and not the original custom one.
=> Fix memory leak when setting pen dash style from custom to predefined

src/graphics-cairo.c, src/graphics-private.h, src/graphics.c, tests/testclip.c
Containers need to maintain the clipping that exists outside them.
I have implemented this by storing the overall clip region outside the current container (`graphics->previous_clip`, `NULL` if not in a container or if no clipping outside) in addition to any clip region set (`graphics->clip`), and then intersecting them in `cairo_SetGraphicsClip()`, `GdipBeginContainer2()` and `GdipGetVisibleClipBounds()` (the three places that need the overall clip). `previous_clip` goes on the save stack on saving, in addition to `clip`.
Alternatively the intersection could be done when modifying the clip and when restoring it off the save stack (four places), but that would mean storing the resulting region as well as the other two, although the overall clip wouldn't need to be stored on the save …
=> Keep clipping inside containers.

src/font.c, src/image.c, tests/gtest.cpp, tests/lsansuppressions.txt, tests/testclip.c, tests/testfont.c, tests/testgpimage.c, tests/testgraphics.c, tests/testgraphicsdraw.c, tests/testgraphicspath.c, tests/testhelpers.h, tests/testlineargradientbrush.c, tests/testmatrix.c, tests/testmetafile.c, tests/testpathgradientbrush.c, tests/testpen.c, tests/testregion.c, tests/testtexturebrush.c
This builds up on fixes by @akoeplinger and fixes remaining memory leak errors reported by the ASAN/LSAN tools. It passes the included test suite (`make check`) and gtest suite (`make -C tests run-gtest`) on fully updated Ubuntu Linux 1804.
=> Various memory leak fixes

src/bitmap-private.h, src/image.c, src/imageattributes.c
Instead of manually fiddling with various pointers inside the `GpBitmap` structure and using fragile manipulation of the Cairo surface object just keep a full `GpBitmap` object copy when any image attributes are applied.
=>  Clean up memory management of gdip_process_bitmap_attributes

src/bmpcodec.c, src/metafile.c
On big-endian systems, various file header elements need to be
byte-swapped.  In a few places, current code used the conversion
function for the wrong data type.
=> Big-endian fix: Header conversion

src/region-bitmap.c
The bitmaps used in region-bitmap.c are created by Cairo in
the the CAIRO_FORMAT_A1 format.  In this format, the order of
1-bit pixels stored in a byte varies depending on endianness.
Fix all accesses to these bits by introducing an is_bit_set
helper macro that takes endianness into account.
=> Big-endian fix: Accessing bitmaps in region-bitmap.c

src/bmpcodec.c
When reading BMP files in 16bppRGB555 or 16bppRGB565 format,
the 16-bit container holding the RGB bits has to be read in
little-endian, even on big-endian systems.
=> Big-endian fix: Reading BMP files

src/pngcodec.c
When reading PNG files, the result must match the Cairo format
CAIRO_FORMAT_ARGB32.  This stores the pixel data as a 32-bit
quantity in native byte order.
Therefore, the PNG decoder must place the bytes in A,R,G,B
order on a big-endian system (as opposed to B,G,R,A on a
little-endian system).  Set up the libpng flags accordingly.
=> Big-endian fix: Reading PNG files

.azure-pipelines.yml, src/libgdiplus.vcxproj
Hopefully a fix for
```
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v150\Microsoft.Cpp.WindowsSDK.targets(46,5): Error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
```
=> Fix Windows build on CI
